### ISSUE TITLE
Pthread Realtime Sched

### ISSUE THREAD

**Issue by anthonyclark-as** [michaelbecker/freertos-addons#13]
Michael,

First off, thanks so much for maintaining this port! I like this better than this one at https://github.com/megakilo/FreeRTOS-Sim (which also supports newer v9.0, etc) since it seems to be a little more sane with pthread calls. I just wanted to include a small bit of code that worked for me and wondered if you saw anything wrong with it.  

In `port.c` you have the block near line ~360 commented out - which as you noted, changes the thread's scheduling policy (main thread primarily, but all child threads by association) via `pthread_setschedparam`. I change it to the few lines below:

```c
int iResult;
struct sched_param iSchedulerPriority = { 1 };

iResult = pthread_setschedparam(pthread_self(), SCHED_RR, &iSchedulerPriority);
configASSERT(iResult == 0);
```
The suggestion you had about using `SCHED_FIFO` is too greedy I believe. I couldn't get it work work at any of the prios listed in `chrt -m`. `SCHED_RR` on the other hand makes more sense conceptually and happened to work without any other changes. Also using `pthread_getschedparam` would make no sense since by default, via `SCHED_OTHER`, the priorities are out of range of `SCHED_FIFO` and `SCHED_RR` - see `chrt -m`. Maybe just forcing the prio low would be fine (or making it configurable).

Anyway, not many people have a use for changing the scheduling policies, but it makes me feel better that things ***seem*** to be more preemptive ;) .

**Comment by michaelbecker** [comment]
First, you are correct about using the result of pthread_getschedparam as an input into pthread_setschedparam. That won't work. You need to set a valid priority in the correct range as you are doing.

In general, I commented out this whole block of code because I realized this approach was problematic. First, using _any_ real time scheduling by default requires the application to run as root, which I'd prefer not to do, and I suspect many others would also prefer. Second. running a process in the real time range and then spinning off multiple threads from it seems fraught with peril if there happens to be a bug. Writing a few infinite loops could quickly lock a machine up, requiring a hard power down to recover. Yes, there are ways to mitigate this, like running a terminal at a higher real time priority than your test app, but things are getting complicated at that point. So I decided to just keep everything simple in the normal boring thread priority range because I felt the Linux port should be used for non-real-time simulation.

I avoided SCHED_RR because at first glance it seemed to be adding an additional level of scheduling to the FreeRTOS simulation. If FreeRTOS was going to provide time slicing, then it should be the one to do so. Having the simulating OS also time slice threads on top of FreeRTOS seemed incorrect. However, after digging into the simulator a bit more, I think it probably doesn't matter much either way. There are locks and checks to handle simulating swapping FreeRTOS threads in and out by using per thread signals. From my testing, the simulated FreeRTOS task scheduling priority appears to be honored without using any real time priorities. I thought I'd leave the commented code available for others to experiment with if they were interested, but I haven't seen the need to invest much further in real time scheduling for the Linux simulator to date.

**Comment by anthonyclark-as** [comment]
Michael,

Thanks for taking the time to reply. Just so you know, you can do `setcap cap_sys_nice=ep ./a.out` to "avoid" using root to launch the application. This way, the application still launches as the user, but you can change the scheduling params.

I've been playing around with some non-free FreeRTOS tracing tools and the results change immensely between using SCHED_OTHER (default) and SCHED_RR. I'm still trying to drill down what exactly is happening. My use case for the FreeRTOS posix/linux ports is try to use them as ACTUAL stand-ins for hardware as much as possible. I'll be putting in plenty of effort to make this port (and the original this is based on) play nice with being rigged up to hardware buses (i2c, etc). When I get some time, I'll upload my patches to this and hopefully we can get a nice simulator / surrogate working (with as much native features as possible).

Thanks again!
