### ISSUE TITLE
Source Code of FreeRTOS

### ISSUE THREAD

**Issue by tsalemy** [michaelbecker/freertos-addons#16]
Hello,

This is less of an issue and more of a question. Is there any way you could also post the source code of the FreeRTOS library you're using? Many of the function names differ from my version, but I want to port over to your version as its fantastic! Thanks for all this great work, I really appreciate the time put into this.

-Thomas

**Comment by michaelbecker** [comment]
Hi Thomas,

All of the work with the wrappers has been done with FreeRTOS 8.2.3, 9.0.0 and now 10.0.0. My goal is to try and keep up to date with the latest versions of FreeRTOS with respect to API changes. If FreeRTOS releases a patch fixing bugs, upgrading it should be transparent to the wrapper library because I'm only using the public API. If the API doesn't change, everything should work.

I've been reluctant to post code from FreeRTOS because I don't want to duplicate the efforts already going on in maintaining it. It should be pretty easy to obtain the latest version(s) or any versions from the FreeRTOS web site - https://www.freertos.org/a00104.html

Best regards,
-Mike
