### ISSUE TITLE
Make Wait method in Thread class static

### ISSUE THREAD

**Issue by maskimthedog** [michaelbecker/freertos-addons#18]
Would it be possible to make the Wait method in the Thread class static so that condition variables could be utilized by threads not instantiated via the Thread class?

**Comment by michaelbecker** [comment]
No, it's not possible. The Condition Variable & Thread classes are interdependent to get the correct behavior, otherwise race conditions can happen. 

I looked into creating a standard C implementation of condition variables that only used the public API of FreeRTOS, but realized that wasn't possible. Getting it right would require integrating into FreeRTOS's internal code.

There's a write-up about condition variables in general at https://www.linkedin.com/pulse/signaling-threads-condition-variables-how-michael-becker/ that describes the race condition.

**Comment by maskimthedog** [comment]
Could you re-architect the condition variable implementation around the FreeRTOS event flag primitive?
