### ISSUE TITLE
Linux simulator port license?

### ISSUE THREAD

**Issue by karlding** [michaelbecker/freertos-addons#22]
Hi Michael,

I had a question about the license used by the Linux port, now that AWS has released FreeRTOS under the MIT license. I noticed that you had started modifying the headers for the C++ wrapper to reflect the MIT license, but the Linux port still remains under the old GPLv2.

Are there plans on relicensing the Linux port under the MIT license?

Also, your `README` still indicates that the C++ wrappers are GPLv2 licensed, should that be changed to reflect the use of the MIT license?

**Comment by michaelbecker** [comment]
When Amazon re-released FreeRTOS under the MIT license, I changed mine to match. I believe I've finished converting a few missed files as of yesterday's release (1.6.0), which includes the README.md and the web site.

However, I cannot change the license of a few of the files, including the Linux port. Regarding the Linux port, this is because I'm not the original copyright holder, William Davy is. Since he released it as GPLv2, it and all derivative works of it must remain GPLv2. Likewise, since the FreeRTOSConfig.h files in the Demos directory were all copied from an older GPLv2 version, I've kept those GPLv2 headers as well.
